services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URI=postgresql://api:test@db/bufware
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bufware
