"""Initial

Revision ID: 6f48c1f1d285
Revises:
Create Date: 2022-05-20 08:38:44.525747

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f48c1f1d285"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kategorie",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nazev", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objednavka",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "stav",
            sa.Enum("OBJEDNANO", "PRIPRAVENO", "VYDANO", "ZRUSENO", name="stav"),
            nullable=True,
        ),
        sa.Column("cena", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "produkt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nazev", sa.String(), nullable=True),
        sa.Column("cena", sa.Float(), nullable=True),
        sa.Column("skryty", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kategorie_produkt",
        sa.Column("produkt_id", sa.Integer(), nullable=True),
        sa.Column("kategorie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kategorie_id"],
            ["kategorie.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produkt_id"],
            ["produkt.id"],
        ),
    )
    op.create_table(
        "obsah_objednavky",
        sa.Column("objednavka_id", sa.Integer(), nullable=True),
        sa.Column("produkt_id", sa.Integer(), nullable=True),
        sa.Column("pocet", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["objednavka_id"],
            ["objednavka.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produkt_id"],
            ["produkt.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("obsah_objednavky")
    op.drop_table("kategorie_produkt")
    op.drop_table("produkt")
    op.drop_table("objednavka")
    op.drop_table("kategorie")
    # ### end Alembic commands ###
