"""Added popis

Revision ID: bd2fbd3e60c7
Revises: 6f48c1f1d285
Create Date: 2022-05-25 10:31:55.625418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd2fbd3e60c7"
down_revision = "6f48c1f1d285"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kategorie_produkt", "produkt_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "kategorie_produkt", "kategorie_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "obsah_objednavky", "objednavka_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "obsah_objednavky", "produkt_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("produkt", sa.Column("popis", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("produkt", "popis")
    op.alter_column(
        "obsah_objednavky", "produkt_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "obsah_objednavky", "objednavka_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "kategorie_produkt", "kategorie_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "kategorie_produkt", "produkt_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
